### PR TITLE
Add Build Targets

### PR DESCRIPTION
**Pull request by 0x715C**
Standalone apps can be built with, 'npm run "win|linux|mac" '.
Default Linux target is AppImage(tested)
Default Mac target is dmg(unable to build on my rig due to walled garden codesigning)
Default Windows is portable executable(tested)(this can also be setup to use codesigning, but I did not test that)

### CODE REVIEW

**Review by spettinichi — APPROVED** [review]
I'm not familiar with AppImage, and don't currently have a Linux install I could use to test this on, but just from reviewing the code changes it looks good. Verified that it is still working in Windows though.

**Comment by spettinichi** [comment]
I tested building the Windows portable, works great! Thanks!

I updated some dependencies in package.json just to remove vulnerabilites when npm install is run. If you don't mind looking over my changes, I'm good to merge this in once somebody has verified that.

**Comment by spettinichi** [comment]
I looked over this again and decided I'll just merge it.

**Comment by 0x715C** [comment]
> I looked over this again and decided I'll just merge it.

Sorry, I've been busy. Linux builds are working for me currently.
I think that the README could say to use 'npm update' after running 'npm install', to update (vulnerable) dependencies.

Just as a side note, and probably not relevant to most people. If you build pacman packages using electron-builder and your SHELL environment variable is not set to bash(mine is set as fish), then the build will fail. The fix is to set the SHELL environment variable to bash(eg. in fish shell prepend 'npm run linux' with 'env SHELL=bash.

**Comment by spettinichi** [comment]
No worries! I didn't realize that sounded kind of impatient, when really I just thought I didn't have the time, and later got some time to go through it more thoroughly.  Good call on the npm update, I just pushed that up.

**Pull request merged**
