### PR TITLE
Startup

### PR DESCRIPTION
**Pull request by spettinichi**
The basics are currently working. The application can be run, and there is framework in place for the stable and beta pages. I created a flag in main.js which can be manually changed to select beta or not. Currently this means we would have to issue two separate apps. I wanted to merge this in while it is working, but want to explore changing between stable in beta in the menu and having it reload the webpage.

### CODE REVIEW

**Comment by spettinichi** [comment]
I added media key support, but have only tested in Windows so far. I'm guessing you have a Mac based on your screenshots? Could you test out the Mac functionality? If it does not work we will have to sort that.
I used this site to ID the values entered using media key presses: http://unixpapa.com/js/testkey.html

**Comment by spettinichi** [comment]
Also added menu items to switch back and forth between beta and stable. By default it loads stable.
I want to explore saving whichever the user was last using to load that upon startup.
Also media keys only work when the window is in focus, so have to explore that as well.

**Comment by jomurgel** [comment]
Thanks for the head start there.  I'll test on Mac and see if things work.  My guess is we'll need to add an OS check in there which wouldn't be too difficult.

**Comment by spettinichi** [comment]
Yeah I figured as much, but didn't want to head down that route until I knew it was an issue. From what I saw the menu might also not work on Mac, since it does menus differently. So need to test menu and media keys. Then need to see if we can get media keys working in the background. Pretty sure that bit will need totally reworked but it is a bit different in electron vs Chrome app, so I went the easy route first.

**Pull request merged**
