### PR TITLE
Linux builds

### PR DESCRIPTION
**Pull request by trivett**
Hello jomurgel!

This unsolicited pull request gives Linux users the ability to install the app as a deb or AppImage so it can be launched without `npm start` and a terminal window hanging. The icon doesn't work quite as expected and I had to update that manually. Works great for me right now apart from the pause media key.

Perhaps in the future someone with a Windows or Mac can add [build rules](https://www.electron.build/configuration/win) for those platforms.

### CODE REVIEW

**Comment by spettinichi** [comment]
Hey sorry for the long delay, but this still builds and runs perfectly fine in Windows, so it appears to not have broken anything there. However, my media keys appear to not work on my current keyboard, so I can't test that at the moment.
I saw you added to do of media keys on Linux, do they not currently work? The current implementation simply captures media_play_pause, media_next, and media_prev then actually clicks the media elements.
Unfortunately, this means that it only works when the window is in focus, which is less useful, but from my research implementing it out of focus in electron is not easy, so this was a halfway solution.
If you have media keys on your keyboard, could you test them in Linux? If not I will try it out, I have Ubuntu now, while I didn't before.

**Comment by spettinichi** [comment]
I merged in a different PR that appears to have caused quite a conflict.. If you can fix this, it should be good to merge after. I will try to take a look at fixing it myself if you don't get to it, but I don't have time tonight.

**Comment by spettinichi** [comment]
The package-lock.json is a mess, so I don't really want to try to fix it using GitHub's web GUI.. the package.json would be an easy fix but since I can't push to your branch I can't fix it locally. Looks like you will have to resolve this before we can merge.

**Comment by jomurgel** [comment]
Functionally I think this works, though I was working on an emulator machine, it feels safe to merge this into master pending some conflict resolutions 👍

**Pull request closed without merging**
